### Common headers for all requests
@baseUrl = https://74j6q7lg6a.execute-api.eu-west-1.amazonaws.com/stage
@contentType = application/json


### Get current currencies
GET https://74j6q7lg6a.execute-api.eu-west-1.amazonaws.com/stage/currencies

### Test CRYPTO to FIAT conversion
GET {{baseUrl}}/orderbook/public/recommendations?type=0&cryptoCurrencyId=TATUM-TRON-USDT&fiatCurrencyId=VES&amount=5&
    amountCurrencyId=TATUM-TRON-USDT
Content-Type: application/json
